name: Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        # TODO: temporarily restrict version due to weird pylint error.
        # See: https://github.com/whonore/proofaday/actions/runs/3699417622/jobs/6266763010.
        python-version: '>=3.6.2 <3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade poetry
        poetry install --no-interaction
    - name: Run linters
      run: poetry run make lint
