name: Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.*'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade poetry
        poetry install --no-interaction
    - name: Run linters
      run: poetry run make lint
