name: Upload Python Package

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and publish
      uses: JRubics/poetry-publish@v1
      env:
        pypi_token: ${{ secrets.PYPI_TOKEN }}
